"
I am the abstract class for styling graphics objects.
I have just the method #apply and i do nothing by default.
"
Class {
	#name : 'TbAbstractStyler',
	#superclass : 'Object',
	#traits : 'TTbDebug',
	#classTraits : 'TTbDebug classTrait',
	#category : 'Turbo-Core-Basic-Support',
	#package : 'Turbo-Core',
	#tag : 'Basic-Support'
}

{ #category : 'as yet unclassified' }
TbAbstractStyler >> apply [
]

{ #category : 'as yet unclassified' }
TbAbstractStyler >> reload [
]
