Class {
	#name : #TbDndTransferMode,
	#superclass : #Object,
	#traits : 'TTbDebug',
	#classTraits : 'TTbDebug classTrait',
	#category : #'Turbo-Core-Space-Support'
}

{ #category : #'as yet unclassified' }
TbDndTransferMode class >> createCopy [
]

{ #category : #'as yet unclassified' }
TbDndTransferMode class >> move [
]

{ #category : #'as yet unclassified' }
TbDndTransferMode class >> none [
]
