Class {
	#name : 'TbElementEventListener',
	#superclass : 'TbEventListener',
	#category : 'Turbo-Core-Events-Handling',
	#package : 'Turbo-Core',
	#tag : 'Events-Handling'
}

{ #category : 'element handlers' }
TbElementEventListener >> elementAddedToParent: anEvent [
]

{ #category : 'element handlers' }
TbElementEventListener >> elementAddedToSuperParent: anEvent [
]

{ #category : 'element handlers' }
TbElementEventListener >> elementBackgroundChanged: anEvent [
]

{ #category : 'element handlers' }
TbElementEventListener >> elementBorderChanged: anEvent [
]

{ #category : 'element handlers' }
TbElementEventListener >> elementExtentChanged: anEvent [
]

{ #category : 'element handlers' }
TbElementEventListener >> elementLayoutChangedChanged: anEvent [
]

{ #category : 'element handlers' }
TbElementEventListener >> elementPositionChanged: anEvent [
]

{ #category : 'element handlers' }
TbElementEventListener >> elementPositionInSpaceChanged: anEvent [
]

{ #category : 'element handlers' }
TbElementEventListener >> elementRemoved: anEvent [
]
