Class {
	#name : 'TbSplineOverScrollerNoneMode',
	#superclass : 'TbSplineOverScrollerMode',
	#category : 'Turbo-Core-Utilities - Scrolling Helpers',
	#package : 'Turbo-Core',
	#tag : 'Utilities - Scrolling Helpers'
}

{ #category : 'updating' }
TbSplineOverScrollerNoneMode >> continueOn: aSplineOverScroller [
	<return: #Boolean>
	
	^ false
]

{ #category : 'updating' }
TbSplineOverScrollerNoneMode >> finishOn: aSplineOverScroller [
]

{ #category : 'initialization' }
TbSplineOverScrollerNoneMode >> initializeOn: aSplineOverScroller [
]

{ #category : 'updating' }
TbSplineOverScrollerNoneMode >> updateOn: aSplineOverScroller [
	<return: #Boolean>

	^ false
]
